/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.Model#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference list.
   * The list contents are of type {@link org.metable.trek.trek.Type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference list.
   * @see org.metable.trek.trek.TrekPackage#getModel_Type()
   * @model containment="true"
   * @generated
   */
  EList<Type> getType();

} // Model
