/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rep</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.Rep#getName <em>Name</em>}</li>
 *   <li>{@link org.metable.trek.trek.Rep#getComponents <em>Components</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getRep()
 * @model
 * @generated
 */
public interface Rep extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.metable.trek.trek.TrekPackage#getRep_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.Rep#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link org.metable.trek.trek.RepComponent}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see org.metable.trek.trek.TrekPackage#getRep_Components()
   * @model containment="true"
   * @generated
   */
  EList<RepComponent> getComponents();

} // Rep
