/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rep Component Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.metable.trek.trek.TrekPackage#getRepComponentType()
 * @model
 * @generated
 */
public interface RepComponentType extends EObject
{
} // RepComponentType
