/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rep Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.RepComponent#getType <em>Type</em>}</li>
 *   <li>{@link org.metable.trek.trek.RepComponent#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getRepComponent()
 * @model
 * @generated
 */
public interface RepComponent extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(RepComponentType)
   * @see org.metable.trek.trek.TrekPackage#getRepComponent_Type()
   * @model containment="true"
   * @generated
   */
  RepComponentType getType();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.RepComponent#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(RepComponentType value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.metable.trek.trek.TrekPackage#getRepComponent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.RepComponent#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // RepComponent
