/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.SystemType#getTypeName <em>Type Name</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getSystemType()
 * @model
 * @generated
 */
public interface SystemType extends RepComponentType
{
  /**
   * Returns the value of the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' attribute.
   * @see #setTypeName(String)
   * @see org.metable.trek.trek.TrekPackage#getSystemType_TypeName()
   * @model
   * @generated
   */
  String getTypeName();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.SystemType#getTypeName <em>Type Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' attribute.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(String value);

} // SystemType
