/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.metable.trek.trek.TrekFactory
 * @model kind="package"
 * @generated
 */
public interface TrekPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "trek";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.metable.org/trek/Trek";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "trek";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TrekPackage eINSTANCE = org.metable.trek.trek.impl.TrekPackageImpl.init();

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.ModelImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TYPE = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.TypeImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Reps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__REPS = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.RepImpl <em>Rep</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.RepImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getRep()
   * @generated
   */
  int REP = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP__NAME = 0;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP__COMPONENTS = 1;

  /**
   * The number of structural features of the '<em>Rep</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.RepComponentImpl <em>Rep Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.RepComponentImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getRepComponent()
   * @generated
   */
  int REP_COMPONENT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP_COMPONENT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP_COMPONENT__NAME = 1;

  /**
   * The number of structural features of the '<em>Rep Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP_COMPONENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.RepComponentTypeImpl <em>Rep Component Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.RepComponentTypeImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getRepComponentType()
   * @generated
   */
  int REP_COMPONENT_TYPE = 4;

  /**
   * The number of structural features of the '<em>Rep Component Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REP_COMPONENT_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.SystemTypeImpl <em>System Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.SystemTypeImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getSystemType()
   * @generated
   */
  int SYSTEM_TYPE = 5;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TYPE__TYPE_NAME = REP_COMPONENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>System Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_TYPE_FEATURE_COUNT = REP_COMPONENT_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.metable.trek.trek.impl.TypeTypeImpl <em>Type Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.metable.trek.trek.impl.TypeTypeImpl
   * @see org.metable.trek.trek.impl.TrekPackageImpl#getTypeType()
   * @generated
   */
  int TYPE_TYPE = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_TYPE__TYPE = REP_COMPONENT_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Type Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_TYPE_FEATURE_COUNT = REP_COMPONENT_TYPE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.metable.trek.trek.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.metable.trek.trek.Model#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Type</em>'.
   * @see org.metable.trek.trek.Model#getType()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Type();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.metable.trek.trek.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link org.metable.trek.trek.Type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.metable.trek.trek.Type#getName()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.metable.trek.trek.Type#getReps <em>Reps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Reps</em>'.
   * @see org.metable.trek.trek.Type#getReps()
   * @see #getType()
   * @generated
   */
  EReference getType_Reps();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.Rep <em>Rep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rep</em>'.
   * @see org.metable.trek.trek.Rep
   * @generated
   */
  EClass getRep();

  /**
   * Returns the meta object for the attribute '{@link org.metable.trek.trek.Rep#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.metable.trek.trek.Rep#getName()
   * @see #getRep()
   * @generated
   */
  EAttribute getRep_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.metable.trek.trek.Rep#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.metable.trek.trek.Rep#getComponents()
   * @see #getRep()
   * @generated
   */
  EReference getRep_Components();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.RepComponent <em>Rep Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rep Component</em>'.
   * @see org.metable.trek.trek.RepComponent
   * @generated
   */
  EClass getRepComponent();

  /**
   * Returns the meta object for the containment reference '{@link org.metable.trek.trek.RepComponent#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.metable.trek.trek.RepComponent#getType()
   * @see #getRepComponent()
   * @generated
   */
  EReference getRepComponent_Type();

  /**
   * Returns the meta object for the attribute '{@link org.metable.trek.trek.RepComponent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.metable.trek.trek.RepComponent#getName()
   * @see #getRepComponent()
   * @generated
   */
  EAttribute getRepComponent_Name();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.RepComponentType <em>Rep Component Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rep Component Type</em>'.
   * @see org.metable.trek.trek.RepComponentType
   * @generated
   */
  EClass getRepComponentType();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.SystemType <em>System Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Type</em>'.
   * @see org.metable.trek.trek.SystemType
   * @generated
   */
  EClass getSystemType();

  /**
   * Returns the meta object for the attribute '{@link org.metable.trek.trek.SystemType#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Name</em>'.
   * @see org.metable.trek.trek.SystemType#getTypeName()
   * @see #getSystemType()
   * @generated
   */
  EAttribute getSystemType_TypeName();

  /**
   * Returns the meta object for class '{@link org.metable.trek.trek.TypeType <em>Type Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type Type</em>'.
   * @see org.metable.trek.trek.TypeType
   * @generated
   */
  EClass getTypeType();

  /**
   * Returns the meta object for the reference '{@link org.metable.trek.trek.TypeType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.metable.trek.trek.TypeType#getType()
   * @see #getTypeType()
   * @generated
   */
  EReference getTypeType_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TrekFactory getTrekFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.ModelImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TYPE = eINSTANCE.getModel_Type();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.TypeImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.getType_Name();

    /**
     * The meta object literal for the '<em><b>Reps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__REPS = eINSTANCE.getType_Reps();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.RepImpl <em>Rep</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.RepImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getRep()
     * @generated
     */
    EClass REP = eINSTANCE.getRep();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REP__NAME = eINSTANCE.getRep_Name();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REP__COMPONENTS = eINSTANCE.getRep_Components();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.RepComponentImpl <em>Rep Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.RepComponentImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getRepComponent()
     * @generated
     */
    EClass REP_COMPONENT = eINSTANCE.getRepComponent();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REP_COMPONENT__TYPE = eINSTANCE.getRepComponent_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REP_COMPONENT__NAME = eINSTANCE.getRepComponent_Name();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.RepComponentTypeImpl <em>Rep Component Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.RepComponentTypeImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getRepComponentType()
     * @generated
     */
    EClass REP_COMPONENT_TYPE = eINSTANCE.getRepComponentType();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.SystemTypeImpl <em>System Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.SystemTypeImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getSystemType()
     * @generated
     */
    EClass SYSTEM_TYPE = eINSTANCE.getSystemType();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_TYPE__TYPE_NAME = eINSTANCE.getSystemType_TypeName();

    /**
     * The meta object literal for the '{@link org.metable.trek.trek.impl.TypeTypeImpl <em>Type Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.metable.trek.trek.impl.TypeTypeImpl
     * @see org.metable.trek.trek.impl.TrekPackageImpl#getTypeType()
     * @generated
     */
    EClass TYPE_TYPE = eINSTANCE.getTypeType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE_TYPE__TYPE = eINSTANCE.getTypeType_Type();

  }

} //TrekPackage
