/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.TypeType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getTypeType()
 * @model
 * @generated
 */
public interface TypeType extends RepComponentType
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see org.metable.trek.trek.TrekPackage#getTypeType_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.TypeType#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

} // TypeType
