/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.metable.trek.trek.Type#getName <em>Name</em>}</li>
 *   <li>{@link org.metable.trek.trek.Type#getReps <em>Reps</em>}</li>
 * </ul>
 *
 * @see org.metable.trek.trek.TrekPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.metable.trek.trek.TrekPackage#getType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.metable.trek.trek.Type#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reps</b></em>' containment reference list.
   * The list contents are of type {@link org.metable.trek.trek.Rep}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reps</em>' containment reference list.
   * @see org.metable.trek.trek.TrekPackage#getType_Reps()
   * @model containment="true"
   * @generated
   */
  EList<Rep> getReps();

} // Type
