/**
 * generated by Xtext 2.31.0
 */
package org.metable.trek.trek.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.metable.trek.trek.RepComponentType;
import org.metable.trek.trek.TrekPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rep Component Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RepComponentTypeImpl extends MinimalEObjectImpl.Container implements RepComponentType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RepComponentTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TrekPackage.Literals.REP_COMPONENT_TYPE;
  }

} //RepComponentTypeImpl
