/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTrekScopeProvider extends DelegatingScopeProvider {
}
