/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.metable.trek.ui.internal.TrekActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TrekExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TrekActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TrekActivator activator = TrekActivator.getInstance();
		return activator != null ? activator.getInjector(TrekActivator.ORG_METABLE_TREK_TREK) : null;
	}

}
