grammar org.metable.trek.Trek with org.eclipse.xtext.common.Terminals

generate trek "http://www.metable.org/trek/Trek"

Model:
	type+=Type*;

Type:
	'type' name=ID '{'
	reps+=Rep*
	'}';

Rep:
	'rep' name=ID '{'
	components+=RepComponent+
	'}';

RepComponent:
	type=RepComponentType name=ID ';';

RepComponentType:
	SystemType | TypeType;

SystemType:
	typeName=('String' | 'int' | 'boolean' | 'char' | 'double');

TypeType:
	type=[Type];
