/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TrekStandaloneSetup extends TrekStandaloneSetupGenerated {

	public static void doSetup() {
		new TrekStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
