/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TrekRuntimeModule extends AbstractTrekRuntimeModule {
}
