/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TrekUiModule extends AbstractTrekUiModule {

	public TrekUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
