/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.metable.trek.parser.antlr.internal.InternalTrekParser;
import org.metable.trek.services.TrekGrammarAccess;

public class TrekParser extends AbstractAntlrParser {

	@Inject
	private TrekGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTrekParser createParser(XtextTokenStream stream) {
		return new InternalTrekParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TrekGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TrekGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
