/*
 * generated by Xtext 2.31.0
 */
package org.metable.trek.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TrekAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/metable/trek/parser/antlr/internal/InternalTrek.tokens");
	}
}
